In [1]:
"""
Q1. Define the multi-dimensional array (2x2 and 3x3) using numpy library and
perform various operations on it (addition, substraction, element-wise 
multiplication, matrix multiplication) without in-built functions.
"""
import numpy as np
# 2x2 matrix
a = np.array([[1,2],[3,4]])
# 3x3 matrix
b = np.array([[3,4,5],[6,7,8],[9,10,11]])
print(a)
print(b)

# Addition
c = [[1,2,3],[4,5,6],[7,8,9]]
d = [[1,2,3],[4,5,6],[7,8,9]]
print("Addition:",c+d)

# Substraction
sub = c-d
print("Substraction:", sub)

# Element-wise Multiplication
output = np.multiply(c,d)
print("Element-wise Multiplication:",output)

#Matrix Multiplication
mat_multiple = np.dot(c,d)
print("Matrix Multiplication:",mat_multiple)

[[1 2]
 [3 4]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
"""
Q2. Write a python program to generate dictionary which consists of first 20
natural numbers as a key. The even number keys must have sqaure of the number as
value while odd number key must have cube of number as value. Print dictionary.
"""
ydict = {}
for i in range(1,21):
  if i%2 == 0:
    ydict[i] = i**2
  else:
    ydict[i] = i
print(ydict)

{1: 1, 2: 4, 3: 3, 4: 16, 5: 5, 6: 36, 7: 7, 8: 64, 9: 9, 10: 100, 11: 11, 12: 144, 13: 13, 14: 196, 15: 15, 16: 256, 17: 17, 18: 324, 19: 19, 20: 400}


In [ ]:
"""
Q3. Define two variables having functional dependency. Plot three graphs(simple
plot, scatter plot and bar graph) between two variables using matplotlib.
"""
import numpy as np
import matplotlib.pyplot as plt

a = np.array([11,22,33,44,55,66,77])
y1 = 3*a**2 - 2

plt.subplot(2,2,1)
plt.plot(a, y1)
plt.subplot(2,2,2)
plt.scatter(a, y1)
plt.subplot(2,2,3)
plt.bar(a, y1)